alter table public."User"
add column if not exists "referralCode" text;

create unique index if not exists user_referral_code_key
on public."User" ("referralCode")
where "referralCode" is not null;

update public."User"
set "referralCode" = 'DF' || lpad(id::text, 6, '0')
where "referralCode" is null
   or trim("referralCode") = '';

create table if not exists public."Referral" (
  id bigint generated by default as identity primary key,
  "referrerUserId" integer not null references public."User"(id) on delete cascade,
  "referredUserId" integer not null references public."User"(id) on delete cascade,
  "referralCode" text not null,
  status text not null default 'registered'
    check (status in ('registered', 'trial', 'approved', 'paid', 'rejected')),
  "rewardCents" integer not null default 500 check ("rewardCents" >= 0),
  "subscriptionId" bigint,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "approvedAt" timestamptz,
  "paidAt" timestamptz,
  constraint referral_unique_referred_user unique ("referredUserId"),
  constraint referral_no_self_referral check ("referrerUserId" <> "referredUserId")
);

create index if not exists referral_referrer_idx
on public."Referral" ("referrerUserId", "createdAt" desc);

create table if not exists public."PixWithdrawalRequest" (
  id bigint generated by default as identity primary key,
  "userId" integer not null references public."User"(id) on delete cascade,
  "amountCents" integer not null check ("amountCents" > 0),
  cpf text not null,
  "pixKey" text not null,
  status text not null default 'requested'
    check (status in ('requested', 'processing', 'paid', 'rejected')),
  "adminNote" text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "paidAt" timestamptz
);

create index if not exists pix_withdrawal_user_idx
on public."PixWithdrawalRequest" ("userId", "createdAt" desc);

create index if not exists pix_withdrawal_status_idx
on public."PixWithdrawalRequest" (status, "createdAt" desc);

create or replace function public.register_referral_by_code(
  p_referred_user_id integer,
  p_referral_code text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_referrer_user_id integer;
  v_code text;
begin
  v_code := upper(trim(coalesce(p_referral_code, '')));

  if v_code = '' then
    return;
  end if;

  if not exists (
    select 1
    from public."User" u
    where u.id = p_referred_user_id
      and u.email = auth.email()
  ) then
    raise exception 'Usuario autenticado nao corresponde ao indicado.';
  end if;

  select id
    into v_referrer_user_id
  from public."User"
  where upper(trim("referralCode")) = v_code
  limit 1;

  if v_referrer_user_id is null then
    raise exception 'Codigo de indicacao invalido.';
  end if;

  if v_referrer_user_id = p_referred_user_id then
    raise exception 'Nao e permitido usar o proprio codigo de indicacao.';
  end if;

  insert into public."Referral" (
    "referrerUserId",
    "referredUserId",
    "referralCode",
    status,
    "rewardCents",
    "updatedAt"
  )
  values (
    v_referrer_user_id,
    p_referred_user_id,
    v_code,
    'registered',
    500,
    now()
  )
  on conflict ("referredUserId") do nothing;
end;
$$;

create or replace function public.approve_referral_on_paid_subscription()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if upper(coalesce(new.status, '')) = 'TRIAL' then
    update public."Referral"
       set status = 'trial',
           "subscriptionId" = new.id,
           "updatedAt" = now()
     where "referredUserId" = new."userId"
       and status = 'registered';
    return new;
  end if;

  if upper(coalesce(new.status, '')) = 'ACTIVE' then
    update public."Referral"
       set status = 'approved',
           "subscriptionId" = new.id,
           "approvedAt" = coalesce("approvedAt", now()),
           "updatedAt" = now()
     where "referredUserId" = new."userId"
       and status in ('registered', 'trial');
  end if;

  return new;
end;
$$;

drop trigger if exists trg_approve_referral_on_subscription on public."Subscription";
create trigger trg_approve_referral_on_subscription
after insert or update of status on public."Subscription"
for each row
execute function public.approve_referral_on_paid_subscription();

alter table public."Referral" enable row level security;
alter table public."PixWithdrawalRequest" enable row level security;

drop policy if exists referral_select_own on public."Referral";
create policy referral_select_own
on public."Referral"
for select
to authenticated
using (
  exists (
    select 1
    from public."User" u
    where u.id = "Referral"."referrerUserId"
      and u.email = auth.email()
  )
);

drop policy if exists pix_withdrawal_select_own on public."PixWithdrawalRequest";
create policy pix_withdrawal_select_own
on public."PixWithdrawalRequest"
for select
to authenticated
using (
  exists (
    select 1
    from public."User" u
    where u.id = "PixWithdrawalRequest"."userId"
      and u.email = auth.email()
  )
);

drop policy if exists pix_withdrawal_insert_own on public."PixWithdrawalRequest";
create policy pix_withdrawal_insert_own
on public."PixWithdrawalRequest"
for insert
to authenticated
with check (
  exists (
    select 1
    from public."User" u
    where u.id = "PixWithdrawalRequest"."userId"
      and u.email = auth.email()
  )
);

grant select on public."Referral" to authenticated;
grant select, insert on public."PixWithdrawalRequest" to authenticated;
grant usage, select on sequence public."Referral_id_seq" to authenticated;
grant usage, select on sequence public."PixWithdrawalRequest_id_seq" to authenticated;
grant execute on function public.register_referral_by_code(integer, text) to authenticated;
